"use client";

import { useState, useRef, useEffect, useCallback } from "react";

export interface SlideCue {
  slide: number;   // 0-indexed
  startSec: number;
}

interface PdfSlideshowProps {
  title: string;
  subtitle: string;
  accent: string;
  slides: { src: string; title?: string }[];
  audioSrc?: string;
  /** Path to cues.json generated by scripts/generate_cues.py */
  cuesSrc?: string;
}

/** Binary search: last cue whose startSec <= t */
function activeCue(cues: SlideCue[], t: number): number {
  let lo = 0, hi = cues.length - 1, result = 0;
  while (lo <= hi) {
    const mid = (lo + hi) >> 1;
    if (cues[mid].startSec <= t) { result = cues[mid].slide; lo = mid + 1; }
    else hi = mid - 1;
  }
  return result;
}

export function PdfSlideshow({
  title, subtitle, accent, slides, audioSrc, cuesSrc,
}: PdfSlideshowProps) {
  const [currentSlide, setCurrentSlide] = useState(0);
  const [isPlaying, setIsPlaying]       = useState(false);
  const [fade, setFade]                 = useState(true);
  const [cues, setCues]                 = useState<SlideCue[]>([]);
  const [duration, setDuration]         = useState(0);
  const [currentTime, setCurrentTime]   = useState(0);

  const audioRef = useRef<HTMLAudioElement | null>(null);
  const rafRef   = useRef<number | null>(null);

  /* ── Load cues.json ──────────────────────────────────────── */
  useEffect(() => {
    if (!cuesSrc) return;
    fetch(cuesSrc)
      .then(r => r.ok ? r.json() : Promise.reject(r.status))
      .then((data: SlideCue[]) => setCues(data.sort((a, b) => a.startSec - b.startSec)))
      .catch(err => console.warn("cues.json not found:", err));
  }, [cuesSrc]);

  /* ── rAF sync loop ───────────────────────────────────────── */
  const tick = useCallback(() => {
    const audio = audioRef.current;
    if (!audio) return;
    const t = audio.currentTime;
    setCurrentTime(t);
    if (cues.length > 0) {
      const idx = activeCue(cues, t);
      setCurrentSlide(prev => {
        if (prev !== idx) {
          setFade(false);
          setTimeout(() => setFade(true), 120);
        }
        return idx;
      });
    }
    if (!audio.paused && !audio.ended) {
      rafRef.current = requestAnimationFrame(tick);
    } else if (audio.ended) {
      setIsPlaying(false);
    }
  }, [cues]);

  const stopRaf = useCallback(() => {
    if (rafRef.current !== null) {
      cancelAnimationFrame(rafRef.current);
      rafRef.current = null;
    }
  }, []);

  useEffect(() => () => stopRaf(), [stopRaf]);

  /* ── Controls ────────────────────────────────────────────── */
  const play = useCallback(() => {
    const audio = audioRef.current;
    if (!audio) return;
    audio.play().then(() => {
      setIsPlaying(true);
      rafRef.current = requestAnimationFrame(tick);
    }).catch(console.warn);
  }, [tick]);

  const pause = useCallback(() => {
    audioRef.current?.pause();
    stopRaf();
    setIsPlaying(false);
  }, [stopRaf]);

  const togglePlay = useCallback(() => {
    isPlaying ? pause() : play();
  }, [isPlaying, pause, play]);

  const seekToSlide = useCallback((idx: number) => {
    const audio = audioRef.current;
    setFade(false);
    setTimeout(() => { setCurrentSlide(idx); setFade(true); }, 120);
    if (audio && cues.length > 0) {
      const cue = cues.find(c => c.slide === idx);
      if (cue) audio.currentTime = cue.startSec;
    }
  }, [cues]);

  const handlePrev = useCallback(() => seekToSlide(Math.max(0, currentSlide - 1)), [seekToSlide, currentSlide]);
  const handleNext = useCallback(() => seekToSlide(Math.min(slides.length - 1, currentSlide + 1)), [seekToSlide, currentSlide, slides.length]);

  /* ── Keyboard ────────────────────────────────────────────── */
  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      if (e.target instanceof HTMLInputElement) return;
      if (e.key === "ArrowLeft")  handlePrev();
      else if (e.key === "ArrowRight") handleNext();
      else if (e.key === " ") { e.preventDefault(); togglePlay(); }
    };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [handlePrev, handleNext, togglePlay]);

  /* ── Derived UI ──────────────────────────────────────────── */
  const progress = duration > 0 ? (currentTime / duration) * 100 : (currentSlide / Math.max(slides.length - 1, 1)) * 100;
  const totalLabel = duration > 0
    ? `${Math.floor(duration / 60)}:${String(Math.floor(duration % 60)).padStart(2, "0")}`
    : `${slides.length} slides`;

  return (
    <div style={{
      background: "rgba(15,23,42,0.85)", backdropFilter: "blur(16px)",
      border: `1px solid ${accent}22`, borderRadius: 16, overflow: "hidden",
      boxShadow: `0 0 40px ${accent}08`,
    }}>
      {/* Header */}
      <div style={{
        padding: "20px 24px 16px",
        borderBottom: `1px solid ${accent}18`,
        display: "flex", justifyContent: "space-between", alignItems: "center",
      }}>
        <div>
          {/* Subtitle removed per request */}
          <h2 style={{ fontSize: 20, fontWeight: 800, color: "#f1f5f9", margin: 0, letterSpacing: "-0.02em" }}>
            {slides[currentSlide]?.title || title}
          </h2>
        </div>
        <div style={{ fontSize: 12, color: "#64748b", fontFamily: "monospace" }}>
          {slides.length} slides · {totalLabel}
          {cues.length > 0 && <span style={{ color: accent, marginLeft: 8 }}>● synced</span>}
        </div>
      </div>

      {/* Slide viewer */}
      <div style={{ position: "relative", width: "100%", paddingBottom: "56.25%", background: "#0a0e1a", overflow: "hidden" }}>
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img
          src={slides[currentSlide]?.src}
          alt={`Slide ${currentSlide + 1}`}
          style={{
            position: "absolute", inset: 0, width: "100%", height: "100%",
            objectFit: "contain", transition: "opacity 0.25s ease",
            opacity: fade ? 1 : 0,
          }}
        />
        {/* Counter */}
        <div style={{
          position: "absolute", top: 12, right: 14,
          background: "rgba(0,0,0,0.8)", backdropFilter: "blur(8px)",
          borderRadius: 8, padding: "4px 10px",
          fontSize: 12, fontWeight: 600, color: "#f1f5f9", fontFamily: "monospace",
        }}>
          {currentSlide + 1} / {slides.length}
        </div>
        {/* Audio time */}
        {duration > 0 && (
          <div style={{
            position: "absolute", top: 12, left: 14,
            background: "rgba(0,0,0,0.8)", backdropFilter: "blur(8px)",
            borderRadius: 8, padding: "4px 10px",
            fontSize: 12, color: "#f1f5f9", fontFamily: "monospace", fontWeight: 600,
          }}>
            {Math.floor(currentTime / 60)}:{String(Math.floor(currentTime % 60)).padStart(2, "0")}
            {" / "}
            {Math.floor(duration / 60)}:{String(Math.floor(duration % 60)).padStart(2, "0")}
          </div>
        )}
      </div>

      {/* Progress bar */}
      <div style={{ height: 3, background: "rgba(255,255,255,0.06)", position: "relative" }}>
        <div style={{
          height: "100%", width: `${progress}%`,
          background: `linear-gradient(90deg, ${accent}, ${accent}aa)`,
          transition: "width 0.15s linear", borderRadius: "0 2px 2px 0",
        }} />
      </div>

      {/* Controls */}
      <div style={{ padding: "12px 24px", display: "flex", alignItems: "center", gap: 12 }}>
        <button onClick={handlePrev} disabled={currentSlide === 0}
          style={{
            background: "rgba(255,255,255,0.06)", border: "1px solid rgba(255,255,255,0.08)",
            borderRadius: 8, padding: "6px 12px", fontSize: 14, cursor: currentSlide === 0 ? "not-allowed" : "pointer",
            color: currentSlide === 0 ? "#334155" : "#94a3b8", transition: "all 0.15s",
          }}>◀</button>

        <div style={{ position: "relative" }}>
          <button onClick={togglePlay}
            style={{
              background: isPlaying ? "rgba(255,255,255,0.08)" : `linear-gradient(135deg, ${accent}, ${accent}cc)`,
              border: `1px solid ${isPlaying ? "rgba(255,255,255,0.1)" : accent}`,
              borderRadius: 8, padding: "6px 18px", fontSize: 13, fontWeight: 700,
              color: isPlaying ? "#e2e8f0" : "#fff", cursor: "pointer",
              display: "flex", alignItems: "center", gap: 6, transition: "all 0.2s",
            }}>
            {isPlaying ? "⏸ Pause" : "▶ Play"}
          </button>
          {!isPlaying && currentSlide === 0 && currentTime === 0 && (
            <>
              <style>{`
                @keyframes pointer-bounce-down {
                  0%, 100% { transform: translate(-50%, 0); }
                  50% { transform: translate(-50%, -8px); }
                }
              `}</style>
              <div style={{
                position: "absolute",
                top: "-48px",
                left: "50%",
                animation: "pointer-bounce-down 1.5s infinite",
                pointerEvents: "none",
                zIndex: 10,
                filter: "drop-shadow(0 2px 4px rgba(0,0,0,0.5))",
                display: "flex",
                flexDirection: "column",
                alignItems: "center",
                color: accent,
                fontWeight: 800,
                whiteSpace: "nowrap"
              }}>
                <span style={{ fontSize: 12, marginBottom: 2, background: "rgba(0,0,0,0.7)", backdropFilter: "blur(4px)", padding: "4px 10px", borderRadius: 12, border: `1px solid ${accent}55` }}>Click to Play</span>
                <span style={{ fontSize: 20 }}>👇</span>
              </div>
            </>
          )}
        </div>

        <button onClick={handleNext} disabled={currentSlide === slides.length - 1}
          style={{
            background: "rgba(255,255,255,0.06)", border: "1px solid rgba(255,255,255,0.08)",
            borderRadius: 8, padding: "6px 12px", fontSize: 14,
            cursor: currentSlide === slides.length - 1 ? "not-allowed" : "pointer",
            color: currentSlide === slides.length - 1 ? "#334155" : "#94a3b8", transition: "all 0.15s",
          }}>▶</button>

        {/* Dot nav */}
        <div style={{ flex: 1, display: "flex", justifyContent: "center", gap: 4, flexWrap: "wrap" }}>
          {slides.map((_, i) => (
            <button key={i} onClick={() => seekToSlide(i)}
              style={{
                width: i === currentSlide ? 20 : 8, height: 8, borderRadius: 4,
                background: i === currentSlide ? accent : i < currentSlide ? `${accent}55` : "rgba(255,255,255,0.1)",
                border: "none", cursor: "pointer", padding: 0, transition: "all 0.2s",
              }} />
          ))}
        </div>

        <span style={{ fontSize: 11, color: "#475569", fontFamily: "monospace" }}>
          {cues.length > 0 ? "audio-synced" : "manual"}
        </span>
      </div>

      {audioSrc && (
        <audio
          ref={audioRef}
          src={audioSrc}
          preload="auto"
          onLoadedMetadata={e => setDuration((e.target as HTMLAudioElement).duration)}
          onEnded={() => { stopRaf(); setIsPlaying(false); }}
        />
      )}
    </div>
  );
}
