"""Narration script for ArenzaTV_Frictionless_Sports_Engagement.pdf (14 slides)."""

FRICTIONLESS_SPORTS_ENGAGEMENT = [
    # Slide 1 — Title: The Future of Frictionless Sports Engagement
    "Good morning. Thank you for your time today. What you're looking at is ArenzaTV — a platform we built to solve a problem that sits at the intersection of three markets that have never been connected before: free sports streaming, local business advertising, and fan loyalty. We believe the infrastructure moment for doing this has arrived, and we're here to show you why.",

    # Slide 2 — Five Colliding Market Forces
    "Before we talk about the product, let's talk about why now. There are five forces converging at the same moment that make this opportunity uniquely timely. FAST mobile streaming now reaches 131 million users in the U.S. and is still accelerating. Local business advertising costs have risen 222% over the past decade — independent bars and restaurants are effectively priced out of every traditional channel. Loyalty programs at the SMB level fail almost universally because of POS hardware complexity. 83% of sports viewers are already on a second screen during every game. And free-to-play gamification is now proven to hold users at 30 to 40% Day-30 retention when the rewards are meaningful. These five forces are not independent trends — they are one open space waiting for a single platform to occupy it.",

    # Slide 3 — The Collapse of RSNs is Driving a FAST Sports Supercycle
    "The structural shift in sports media is accelerating faster than most people realize. Regional sports networks — the cable bundles that once carried local MLB, NBA, and NHL games — are collapsing. Main Street Sports, formerly Diamond Sports, has left 29 MLB teams without a local broadcast home. That audience has not disappeared. It has moved to mobile. Gen Z averages over six hours per day on their phones and only 54% ever watch a full game from start to finish. The FAST market is growing at a 21% compounded annual rate and is projected to reach $31.8 billion by 2030. This is not a niche shift — it is a full-scale migration of the sports audience away from the living room TV to the commute, the bar, and the second screen. ArenzaTV is built exactly for where that audience now lives.",

    # Slide 4 — Local Businesses Are Locked Out of Ads and Trapped by POS Loyalty
    "Here is the problem on the merchant side, and it is equally structural. A 30-second regional sports TV slot costs between $15,000 and $100,000. The average independent sports bar has a total advertising budget of around $2,000. That is not a gap — that is a wall. So local businesses have no real way into sports advertising. And when they try loyalty programs instead, they hit a different wall: POS hardware integration that requires expensive equipment, staff retraining, and months of setup time. Loyalty programs deliver a proven 4.8x ROI when they work. But for independent merchants, they almost never get the chance to work, because the friction of getting started is too high. That is the problem we are solving.",

    # Slide 5 — Eliminating the Hardware Barrier: The QR Hub Leap
    "This slide shows the core of what makes ArenzaTV structurally different from every existing loyalty solution. Legacy POS loyalty systems require expensive hardware integration, multi-step enrollment forms, high monthly SaaS fees, and physical cards or phone numbers at checkout. The ArenzaTV QR Hub requires exactly one thing from the merchant: the smartphone already in their pocket. The fan's unique QR code serves as their identity, their reward wallet, and a location-based discovery tool that connects them to nearby participating businesses. Over 100 million Americans will use QR codes comfortably in 2026 — this is not new behavior we are asking anyone to learn. We are simply giving it a purpose that drives real commerce.",

    # Slide 6 — Second-Screen Gamification Turns Distraction into Purchase Intent
    "83% of American TV viewers are already using a second device while they watch. 65% are specifically using it to look up something related to what they are watching. That behavior already exists. What does not exist yet is a product that channels that second-screen attention toward local commerce in real time. ArenzaTV's free-to-play prediction mechanic — pick'em polls, trivia, live reactions — gives fans a reason to stay in the app during the game. There is no cash wagering, no gambling classification risk. Just engagement that earns points. And the data shows this works: best-in-class free-to-play sports apps achieve 30 to 40% Day-30 retention, which is double the industry average for consumer apps. The hook is live sports. The retention engine is the reward.",

    # Slide 7 — The B2B2C Ecosystem Resolves the Market Fragmentation
    "This diagram is the heart of the business. On the left, broadcasters bring content and share ad revenue with ArenzaTV. In the center, ArenzaTV operates the QR hub and the split-screen engagement layer. At the top, fans bring their attention and earn engagement points during the game. At the bottom, local SMBs sponsor rewards and receive verified foot traffic back to their venues. Every party gives something and gets something of greater value in return. Broadcasters monetize their audience more deeply. Fans get free sports and real rewards. Local businesses get affordable, attributable customer acquisition for the first time. ArenzaTV earns from the ad revenue share and from merchant sponsorship fees. This is not a one-sided marketplace — it is a flywheel where each participant strengthens the value for all the others.",

    # Slide 8 — The Generational Infrastructure Moat: DePIN Powered by MOQ
    "This is where the technical differentiation becomes a long-term moat. Through a strategic partnership with Caton Technology, ArenzaTV is building on Media over QUIC — MOQ — a next-generation protocol that delivers sub-second video latency. To put that in context: every existing competitor streams on HLS or DASH at 6 to 12 seconds of latency. At 6 seconds of delay, a game moment has already been discussed on Twitter before your prediction question can even appear on screen. At sub-second latency, the prediction, the live moment, and the reward are synchronized. That synchronization is what makes the gamification feel real rather than lag-compensated. The DePIN edge network architecture also gives this platform decentralized resilience at scale — built specifically for high-density, real-time live sports engagement across thousands of concurrent sessions.",

    # Slide 9 — The Frictionless Attribution Loop in Action
    "This is the product experience in three steps. Step one: the fan makes a prediction during the game and earns points. Step two: those points accumulate automatically in their unique ArenzaTV QR code — no action required. Step three: the fan walks into a participating bar or restaurant and shows their QR code. The merchant scans it with their own phone in under five seconds. Loop closed. No POS terminal. No token settlement for the merchant. No app-to-app integration. Just a smartphone camera and a QR code. And on the back end, that scan pings verified foot-traffic attribution back to the ad sponsor — giving them proof that a fan who watched their broadcast actually walked through a door. That is the closed loop that no existing platform in this space can offer.",

    # Slide 10 — Stacked Revenue Streams Replace Traditional SaaS Models
    "By removing the upfront merchant SaaS fee entirely, we remove the adoption barrier that kills most B2B tools at the SMB level. We do not need merchants to write a check to get started. Revenue comes from three stacked streams. First, ad revenue share from FAST distribution partners — typically a 50/50 split on the ad inventory we help monetize. Second, hyperlocal sponsorship fees from SMBs who pay to feature their rewards to fans in their geographic area during relevant game moments. Third, optional premium features for high-volume venues that want advanced analytics and placement. The first two streams fund the reward pool and the platform operations. The third stream scales with merchant sophistication over time.",

    # Slide 11 — A Fragmented FAST Landscape Offers Immediate Partnership Targets
    "The partnership opportunity is open right now because the market is fragmented and rights holders are actively looking for monetization partners. E.W. Scripps launched a dedicated sports FAST channel in March 2026 — covering PWHL, NWSL, MLB, and NHL — with State Farm as a founding sponsor. That is the model we sit on top of. Pluto TV, Tubi, and Xumo are the major ad-supported distribution platforms that carry sports content today. Local broadcast affiliates already run their own FAST extensions and are looking for digital co-sell partners. And the RSN collapse has left 29 MLB franchises and numerous NHL and NBA properties in active rights transition. These are not door-knock cold-call prospects — they are rights holders who need exactly what ArenzaTV brings: a distribution and engagement layer that makes their inventory more valuable.",

    # Slide 12 — Proactive Mitigations for Key Structural Risks
    "We want to be direct about the three structural risks in this business and how we have designed around each one. First, content rights resistance from tier-one leagues: we avoid this entirely in year one by targeting tier-two and tier-three properties — NWSL, Big Sky conference, local OTA affiliates — where CPM expectations are calibrated to FAST realities and rights holders are eager to experiment. Second, consumer cold-start: we do not need anyone to discover ArenzaTV from scratch. We distribute the engagement layer inside existing FAST viewership pipelines and convert current viewers through on-screen QR prompts. The audience is already watching. Third, App Store compliance: our mechanic is strictly non-wagering. Points are earned through social predictions and redeemed at local businesses — no cash, no crypto payout. That design keeps us fully outside gambling classification under Apple's guidelines.",

    # Slide 13 — A Multi-Billion Dollar Disruption Opportunity
    "Let me put the market size in context. The global sports streaming market reaches $83.6 billion by 2030. The total FAST market hits $31.8 billion that same year. Local and regional sports TV ad spend is $20 billion per year today — and that is the primary disruption target, because it is the market that existing tools have completely failed to serve. The sports fan loyalty segment alone projects to $17.8 billion by 2033 at a 12.1% compound annual rate. ArenzaTV does not have to win all of these markets. It sits at the intersection of all four, and a small slice of each of them represents a very large business.",

    # Slide 14 — Redefining Local Sports Monetization at Scale
    "Let me close with the three-sentence version of why this matters. The demand is validated — 131 million FAST viewers and a $20 billion local ad market that has no viable access point for small businesses. The ecosystem is frictionless — we eliminate POS hardware entirely and close the attribution loop with nothing more than a smartphone and a QR code. And the moat is real — we are building on the world's first Media over QUIC DePIN architecture, powered by Caton Technology, which synchronizes live sports moments with fan engagement at sub-second latency that no competitor can match today. We are ready to put this in front of the right investors and broadcaster partners. Thank you.",
]
