/**
 * businessData.ts — Demo business seed data
 * Fictional businesses near Atlantic Beach / Long Beach, NY (ZIP 11509)
 * for the Arenza Dual-Screen simulator demo.
 */
import type { BusinessListing } from './sharedTypes';

export const DEMO_BUSINESSES: BusinessListing[] = [
  {
    id: 'b1',
    name: "Rocco's Pizzeria",
    category: 'pizza',
    tagline: 'Slice by slice, game by game.',
    address: '123 Atlantic Ave',
    city: 'Atlantic Beach',
    state: 'NY',
    zip: '11509',
    lat: 40.5873,
    lng: -73.7270,
    phone: '+15165550100',
    rating: 4.7,
    reviewCount: 83,
    distanceMiles: 0.3,
    primaryColor: '#e63946',
    emoji: '🍕',
    hours: { mon:'11:00-22:00', tue:'11:00-22:00', wed:'11:00-22:00', thu:'11:00-22:00', fri:'11:00-23:00', sat:'11:00-23:00', sun:'12:00-21:00' },
    activeOffer: {
      headline: 'Buy 1 Slice Get 1 FREE — Tonight Only',
      dealType: 'bogo',
      dealValue: 'Free Slice',
      expiresAt: new Date(Date.now() + 8 * 3600 * 1000).toISOString(),
      promoCode: 'ARENZA-BOGO',
    },
    membership: {
      enabled: true,
      cardName: "Rocco's Club",
      stampsRequired: 10,
      reward: 'Free whole pizza after 10 slices',
      perks: ['10% off always', 'Free birthday slice', 'Priority pickup'],
    },
    orderEnabled: true,
    orderUrl: 'https://roccos-demo.arenza.tv/order',
    arenzaPointsAccepted: true,
    targetTiers: ['T1','T2','T3','T4','T5'],
  },
  {
    id: 'b2',
    name: "O'Brien's Sports Bar",
    category: 'sports_bar',
    tagline: 'Best seat in the house, every game.',
    address: '45 Park St',
    city: 'Long Beach',
    state: 'NY',
    zip: '11561',
    lat: 40.5881,
    lng: -73.6574,
    phone: '+15165550200',
    rating: 4.5,
    reviewCount: 127,
    distanceMiles: 1.2,
    primaryColor: '#2d6a4f',
    emoji: '🍺',
    hours: { mon:'12:00-02:00', tue:'12:00-02:00', wed:'12:00-02:00', thu:'12:00-02:00', fri:'12:00-04:00', sat:'11:00-04:00', sun:'11:00-01:00' },
    activeOffer: {
      headline: 'Happy Hour: $4 Drafts All Game Long',
      dealType: 'percent_off',
      dealValue: '$4 Draft Beers',
      expiresAt: new Date(Date.now() + 6 * 3600 * 1000).toISOString(),
    },
    membership: {
      enabled: true,
      cardName: "O'Brien's VIP",
      reward: 'Free pitcher every 5th visit',
      perks: ["No cover charge", "Members' discount on food", "Priority seating on game night"],
    },
    orderEnabled: false,
    arenzaPointsAccepted: true,
    targetTiers: ['T1','T2','T3','T6','T7'],
  },
  {
    id: 'b3',
    name: 'Shore Diner',
    category: 'diner',
    tagline: 'All-day breakfast, all-night energy.',
    address: '210 Beach Ave',
    city: 'Atlantic Beach',
    state: 'NY',
    zip: '11509',
    lat: 40.5862,
    lng: -73.7295,
    phone: '+15165550300',
    rating: 4.3,
    reviewCount: 241,
    distanceMiles: 0.5,
    primaryColor: '#f59e0b',
    emoji: '🍳',
    hours: { mon:'06:00-22:00', tue:'06:00-22:00', wed:'06:00-22:00', thu:'06:00-22:00', fri:'06:00-23:00', sat:'06:00-23:00', sun:'06:00-21:00' },
    activeOffer: {
      headline: '20% Off Game Day Breakfast Platter',
      dealType: 'percent_off',
      dealValue: '20% off',
      expiresAt: new Date(Date.now() + 10 * 3600 * 1000).toISOString(),
      promoCode: 'GAMEDAY20',
    },
    membership: {
      enabled: true,
      cardName: 'Shore Regulars',
      stampsRequired: 8,
      reward: 'Free breakfast after 8 visits',
      perks: ['Free coffee refills', 'Express seating', '5% off always'],
    },
    orderEnabled: true,
    orderUrl: 'https://shorediner-demo.arenza.tv/order',
    arenzaPointsAccepted: true,
    targetTiers: ['T4','T5','T6','T7','T8'],
  },
  {
    id: 'b4',
    name: 'Coastal Coffee Co.',
    category: 'coffee',
    tagline: 'Fuel your fandom.',
    address: '78 Neptune Blvd',
    city: 'Long Beach',
    state: 'NY',
    zip: '11561',
    lat: 40.5894,
    lng: -73.6581,
    phone: '+15165550400',
    rating: 4.8,
    reviewCount: 312,
    distanceMiles: 1.4,
    primaryColor: '#7c5c3e',
    emoji: '☕',
    hours: { mon:'06:00-18:00', tue:'06:00-18:00', wed:'06:00-18:00', thu:'06:00-18:00', fri:'06:00-19:00', sat:'07:00-19:00', sun:'07:00-17:00' },
    activeOffer: {
      headline: 'Free pastry with any latte — Game Day Special',
      dealType: 'free_item',
      dealValue: 'Free Pastry',
      expiresAt: new Date(Date.now() + 12 * 3600 * 1000).toISOString(),
    },
    membership: {
      enabled: true,
      cardName: 'Coastal Beans Card',
      stampsRequired: 9,
      reward: 'Free drink after 9 stamps',
      perks: ['Barista priority lane', 'Monthly free drink', 'Seasonal specials access'],
    },
    orderEnabled: false,
    arenzaPointsAccepted: true,
    targetTiers: ['T2','T3','T4','T5','T6'],
  },
  {
    id: 'b5',
    name: 'Atlantic Seafood Grill',
    category: 'seafood',
    tagline: 'Fresh off the boat. Straight to your table.',
    address: '5 Oceanview Dr',
    city: 'Atlantic Beach',
    state: 'NY',
    zip: '11509',
    lat: 40.5855,
    lng: -73.7315,
    phone: '+15165550500',
    rating: 4.6,
    reviewCount: 178,
    distanceMiles: 0.8,
    primaryColor: '#0ea5e9',
    emoji: '🦞',
    hours: { mon:'closed', tue:'12:00-21:00', wed:'12:00-21:00', thu:'12:00-21:00', fri:'12:00-22:00', sat:'11:00-22:00', sun:'11:00-20:00' },
    activeOffer: {
      headline: '$10 Off Any Entree Over $40',
      dealType: 'coupon',
      dealValue: '$10 off',
      expiresAt: new Date(Date.now() + 24 * 3600 * 1000).toISOString(),
      promoCode: 'ARENZA10',
    },
    orderEnabled: true,
    orderUrl: 'https://atlanticseafood-demo.arenza.tv/order',
    arenzaPointsAccepted: true,
    targetTiers: ['T1','T2','T9'],
  },
  {
    id: 'b6',
    name: 'Iron Coast Gym',
    category: 'gym',
    tagline: 'Train hard. Win big.',
    address: '320 Mott Ave',
    city: 'Long Beach',
    state: 'NY',
    zip: '11561',
    lat: 40.5912,
    lng: -73.6602,
    phone: '+15165550600',
    rating: 4.4,
    reviewCount: 95,
    distanceMiles: 1.9,
    primaryColor: '#7c3aed',
    emoji: '💪',
    hours: { mon:'05:00-22:00', tue:'05:00-22:00', wed:'05:00-22:00', thu:'05:00-22:00', fri:'05:00-21:00', sat:'07:00-19:00', sun:'08:00-18:00' },
    activeOffer: {
      headline: '7-Day Free Trial — No Credit Card',
      dealType: 'free_item',
      dealValue: '7-Day Free Pass',
      expiresAt: new Date(Date.now() + 72 * 3600 * 1000).toISOString(),
    },
    membership: {
      enabled: true,
      cardName: 'Iron Coast Member',
      reward: '1 free PT session per month',
      perks: ['24/7 access key fob', 'Guest passes', 'Class discounts', 'Free towel service'],
    },
    orderEnabled: false,
    arenzaPointsAccepted: false,
    targetTiers: ['T1','T2','T7','T8'],
  },
];

/** Get businesses sorted by distance (closest first) */
export function getSortedByDistance(businesses: BusinessListing[] = DEMO_BUSINESSES): BusinessListing[] {
  return [...businesses].sort((a, b) => (a.distanceMiles ?? 99) - (b.distanceMiles ?? 99));
}

/** Get businesses with an active offer */
export function getBusinessesWithOffer(businesses: BusinessListing[] = DEMO_BUSINESSES): BusinessListing[] {
  return businesses.filter(b => b.activeOffer);
}

/** Filter by viewer tier targeting */
export function getBusinessesForTier(tier: string, businesses: BusinessListing[] = DEMO_BUSINESSES): BusinessListing[] {
  return businesses.filter(b => !b.targetTiers || b.targetTiers.includes(tier));
}
